# Generated by Django 5.2.1 on 2025-06-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_all_users", "Can view all users"),
                    ("can_ban_users", "Can ban users"),
                ]
            },
        ),
    ]
