# Generated by Django 5.2.1 on 2025-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("MANAGER", "Manager")],
                default="USER",
                max_length=7,
            ),
        ),
    ]
