# Generated by Django 5.2.1 on 2025-06-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
