# Generated by Django 5.2.1 on 2025-05-31 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(max_length=255)),
                ("comment", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("email",),
                "indexes": [
                    models.Index(
                        fields=["owner"], name="clients_cli_owner_i_89d16e_idx"
                    ),
                    models.Index(fields=["email"], name="clients_cli_email_56b9fc_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "email"), name="unique_client_per_owner"
                    )
                ],
            },
        ),
    ]
