# Generated by Django 5.2.1 on 2025-06-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("email",),
                "permissions": [("can_view_all_clients", "Can view all Clients")],
            },
        ),
    ]
