# Generated by Django 5.2.1 on 2025-06-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("email",)},
        ),
    ]
