# Generated by Django 5.2.1 on 2025-06-06 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["owner"], name="mail_messag_owner_i_13f0c8_idx"),
        ),
    ]
