# Generated by Django 5.2.1 on 2025-06-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0002_message_mail_messag_owner_i_13f0c8_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("subject",),
                "permissions": [("can_view_all_messages", "Can view all Messages")],
            },
        ),
    ]
