# Generated by Django 5.2.1 on 2025-06-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0003_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("subject",)},
        ),
    ]
