# Generated by Django 5.2.1 on 2025-06-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0001_initial"),
        ("mailings", "0002_mailing_owner_message_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mail_messages.message"
            ),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
