# Generated by Django 5.2.1 on 2025-06-06 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("mail_messages", "0002_message_mail_messag_owner_i_13f0c8_idx"),
        ("mailings", "0004_alter_mailingattempt_mailing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["owner"], name="mailings_ma_owner_i_001dc3_idx"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["status"], name="mailings_ma_status_8e6188_idx"),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(
                fields=["timestamp"], name="mailings_ma_timesta_a41580_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(fields=["status"], name="mailings_ma_status_c690eb_idx"),
        ),
    ]
