# Generated by Django 5.2.1 on 2025-06-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_mailing_mailings_ma_owner_i_001dc3_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Can view all mailings"),
                    ("can_disable_mailings", "Can disable Mailings"),
                ]
            },
        ),
    ]
