# Generated by Django 5.2.1 on 2025-06-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={},
        ),
    ]
