# Generated by Django 5.2.1 on 2025-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0007_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
