# Generated by Django 5.2.1 on 2025-06-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0008_mailing_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["start_time", "end_time"]},
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={"ordering": ["-timestamp"]},
        ),
    ]
