# Generated by Django 5.2.1 on 2025-06-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_client_options"),
        ("mailings", "0009_alter_mailing_options_alter_mailingattempt_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="clients.client",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(
                fields=["mailing"], name="mailings_ma_mailing_591bf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(
                fields=["client"], name="mailings_ma_client__ccae5e_idx"
            ),
        ),
    ]
